const { app, BrowserWindow } = require('electron');
const path = require('node:path');
const fs = require('node:fs/promises');
const assert = require('node:assert/strict');
const { pathToFileURL } = require('node:url');
const root = path.resolve(__dirname, '..');
app.setPath('userData', path.join(root, 'artifacts', 'ui-userdata'));
app.disableHardwareAcceleration();
app.whenReady().then(async () => {
  const { startServer } = await import(pathToFileURL(path.join(root, 'src/server.mjs')).href);
  const backend = await startServer({ directory: path.join(root, 'artifacts', 'ui-data-' + Date.now()) });
  const win = new BrowserWindow({ width: 1510, height: 1000, show: false, webPreferences: { offscreen: true, contextIsolation: true, nodeIntegration: false } });
  const errors = []; win.webContents.on('console-message', event => { if (event.level === 'error') errors.push(event.message); });
  const js = code => win.webContents.executeJavaScript(code);
  const until = async expression => { for (let i = 0; i < 150; i++) { if (await js(expression)) return; await new Promise(r => setTimeout(r, 100)); } throw new Error('UI timed out: ' + expression); };
  const click = selector => js(`document.querySelector(${JSON.stringify(selector)}).click()`);
  try {
    await win.loadURL(backend.url); await until('!!document.querySelector("#open-lab")');
    await fs.mkdir(path.join(root, 'artifacts/screenshots'), { recursive: true });
    await fs.writeFile(path.join(root, 'artifacts/screenshots/overview.png'), (await win.webContents.capturePage()).toPNG());
    await click('#open-lab'); await until('!!document.querySelector("#scan-new")');
    assert.ok(await js('!!document.querySelector("#scan-backend option[value=ng]")'));
    await js('document.querySelector("#scan-backend").value="host"');
    await click('#scan-new'); await until('document.querySelector("#scan-results").textContent.includes("0x100000100")');
    assert.ok(await js('document.querySelector("#scan-progress").textContent.includes("HOST")'));
    await click('[data-address="0x100000100"]'); await until('document.querySelector("#hex-output").textContent.includes("64 00 00 00")');
    await click('[data-watch="0x100000100"]'); await until('document.querySelector("#watch-results").textContent.includes("100")');
    await fs.writeFile(path.join(root, 'artifacts/screenshots/memory.png'), (await win.webContents.capturePage()).toPNG());
    await click('#demo-tick'); await js('document.querySelector("#scan-mode").value="decreased"'); await click('#scan-next');
    await until('document.querySelector("#result-meta").textContent.includes("pass 2") && document.querySelector("#scan-results").textContent.includes("93")');
    await click('[data-page="map"]'); await click('#maps-select'); await click('#dump-selected');
    await until('document.querySelector("#dump-list")?.textContent.includes("Scan offline")');
    await fs.writeFile(path.join(root, 'artifacts/screenshots/dumps.png'), (await win.webContents.capturePage()).toPNG());
    await click('[data-offline]'); await js('document.querySelector("#scan-value").value="93"'); await click('#scan-new');
    await until('document.querySelector("#scan-results").textContent.includes("0x100000100")');
    for (const page of ['folder', 'pkg', 'payload', 'mcp', 'activity', 'home']) { await click(`[data-page="${page}"]`); assert.ok(await js('document.querySelector("h1").textContent.length > 5')); }
    await click('[data-page="pkg"]'); assert.ok(await js('!!document.querySelector("#pkg-install") && !!document.querySelector("#pkg-path")'));
    const pkgFolder=path.join(root,'artifacts','ui-packages');await fs.mkdir(path.join(pkgFolder,'nested'),{recursive:true});
    const pkgData=Buffer.alloc(0x3000);pkgData.writeUInt32BE(0x7f434e54);pkgData.write('UP0002-CUSA57548_00-TESTPACKAGE00001',0x40);pkgData.writeUInt32BE(0x1a,0x74);pkgData.writeBigUInt64BE(0x3000n,0x430);
    await fs.writeFile(path.join(pkgFolder,'Base game.pkg'),pkgData);pkgData.writeUInt32BE(0x40000000,0x78);await fs.writeFile(path.join(pkgFolder,'nested','Update.pkg'),pkgData);await fs.writeFile(path.join(pkgFolder,'Incomplete.pkg'),'incomplete');
    await js(`void(window.desktop={chooseFolder:async()=>${JSON.stringify(pkgFolder)}})`);await click('#pkg-add-folder');
    await until('document.querySelector("#pkg-queue").textContent.includes("3 packages")');
    assert.ok(await js('document.querySelector("#pkg-queue").textContent.includes("Invalid PKG") && document.querySelector("#pkg-queue").textContent.includes("Update.pkg")'));
    await click('#pkg-add-folder');assert.equal(await js('document.querySelectorAll("[data-pkg-remove]").length'),3);
    await click('[data-pkg-remove]');await until('document.querySelectorAll("[data-pkg-remove]").length===2');
    await js('document.querySelector("#toasts").replaceChildren();document.querySelector("#pkg-add-folder").scrollIntoView({block:"center"});');
    await fs.writeFile(path.join(root, 'artifacts/screenshots/pkg-installer.png'), (await win.webContents.capturePage()).toPNG());
    await click('#top-connect');await until('document.querySelector("#top-connect").textContent.includes("Connect console")');
    await click('[data-page="home"]');
    await js('document.querySelector("#console-platform").value="ps5";document.querySelector("#console-platform").dispatchEvent(new Event("change",{bubbles:true}))');
    assert.equal(await js('document.querySelector("#payload-port").value'),'9021');
    assert.equal(await js('document.querySelector("#firmware-profile").value'),'13.60');
    await click('#save-profile');await until('document.querySelector(".hero").textContent.includes("PLAYSTATION 5")');
    assert.equal(backend.workbench.profile.platform,'ps5');
    await fs.writeFile(path.join(root,'artifacts/screenshots/ps5-overview.png'),(await win.webContents.capturePage()).toPNG());
    await click('[data-page="payload"]');assert.ok(await js('document.querySelector("#main").textContent.includes("PS5 ELF Loader")'));
    await click('[data-page="pkg"]');assert.ok(await js('!!document.querySelector("#pkg-load") && !!document.querySelector("#pkg-install")'));assert.equal(await js('document.querySelector("#pkg-receiver-port").value'),'9698');assert.equal(await js('document.querySelector("#pkg-mode").options.length'),1);
    assert.ok(await js('document.querySelector("#main").textContent.includes("PS5 companion")'));assert.ok(await js('!!document.querySelector("#pkg-pause") && !!document.querySelector("#pkg-resume")'));
    await click('[data-page="console"]');assert.ok(await js('document.querySelector("#console-load").textContent.includes("PS5 companion")'));
    await until('document.querySelector("#console-compatibility").textContent.includes("PS5")');
    const game=path.join(root,'artifacts','ui-shadow-game');await fs.mkdir(path.join(game,'sce_sys'),{recursive:true});await fs.writeFile(path.join(game,'sce_sys/param.json'),JSON.stringify({titleId:'PPSA12345',titleName:'ShadowMount UI fixture'}));await fs.writeFile(path.join(game,'eboot.bin'),'fixture');
    await click('[data-page="shadow"]');await until('!!document.querySelector("#shadow-folder")');
    await js(`void(window.desktop={chooseFolder:async()=>${JSON.stringify(game)}})`);await click('#shadow-folder');await until('document.querySelector("#shadow-queue").textContent.includes("PPSA12345")');
    assert.ok(await js('document.querySelector("#shadow-start").disabled'));assert.ok(await js('!!document.querySelector("#shadow-prepare")'));assert.ok(await js('!!document.querySelector("#shadow-repair")'));
    await fs.writeFile(path.join(root,'artifacts/screenshots/shadowmount.png'),(await win.webContents.capturePage()).toPNG());
    await click('[data-shadow-remove]');await until('document.querySelector("#shadow-queue").textContent.includes("empty")');
    await click('[data-page="folder"]');assert.ok(await js('!!document.querySelector("#ftp-path")'));
    assert.deepEqual(errors, []); console.log('PASS: PS4 simulated scan/dump flow and PS5 profile, ELF page, FTP page and native-control restrictions.');
    await backend.close(); win.destroy(); app.exit(0);
  } catch (e) { console.error(e.stack); try { await fs.writeFile(path.join(root, 'artifacts/screenshots/failure.png'), (await win.webContents.capturePage()).toPNG()); } catch {} await backend.close(); app.exit(1); }
});
