// Model facts from https://github.com/DurtyFree/gta-v-data-dumps/blob/master/vehicles.json
// Generated by scripts/build-gta-vehicles.mjs; availability is checked in-game.
#pragma once
#define VEHICLE_CANDIDATES 881
static const char vehicle_text[] =
"811\0"
"Adder\0"
"Autarch\0"
"Banshee 900R\0"
"Bullet\0"
"Champion\0"
"Cheetah\0"
"Cyclone\0"
"Cyclone II\0"
"Deveste Eight\0"
"Emerus\0"
"Entity MT\0"
"Entity XF\0"
"Entity XXR\0"
"ETR1\0"
"FMJ\0"
"FMJ MK V\0"
"Furia\0"
"GP1\0"
"Ignus\0"
"Infernus\0"
"Itali GTB\0"
"Itali GTB Custom\0"
"Krieger\0"
"LM87\0"
"Luiva\0"
"Nero\0"
"Nero Custom\0"
"Osiris\0"
"Penetrator\0"
"Pipistrello\0"
"RE-7B\0"
"Reaper\0"
"Rocket Voltic\0"
"S80RR\0"
"SC1\0"
"Scramjet\0"
"Sultan RS\0"
"Suzume\0"
"T20\0"
"Taipan\0"
"Tempesta\0"
"Tezeract\0"
"Thrax\0"
"Tigon\0"
"Torero XO\0"
"Turismo Omaggio\0"
"Turismo R\0"
"Tyrant\0"
"Tyrus\0"
"Vacca\0"
"Vagner\0"
"Vigilante\0"
"Virtue\0"
"Visione\0"
"Voltic\0"
"Weaponized Ignus\0"
"X-treme\0"
"X80 Proto\0"
"XA-21\0"
"Zeno\0"
"Zentorno\0"
"Zorrusso\0"
"10F\0"
"10F Widebody\0"
"300R\0"
"8F Drafter\0"
"9F\0"
"9F Cabrio\0"
"Alpha\0"
"Apocalypse ZR380\0"
"Banshee\0"
"Banshee GTS\0"
"Bestia GTS\0"
"Blista Compact\0"
"Buffalo\0"
"Buffalo S\0"
"Calico GTF\0"
"Carbonizzare\0"
"Comet\0"
"Comet Retro Custom\0"
"Comet S2\0"
"Comet S2 Cabrio\0"
"Comet Safari\0"
"Comet SR\0"
"Coquette\0"
"Coquette D10\0"
"Coquette D5\0"
"Corsita\0"
"Cypher [cypher]\0"
"Cypher [driftcypher]\0"
"Drift Tampa [drifttampa]\0"
"Drift Tampa [tampa2]\0"
"Elegy Retro Custom\0"
"Elegy RH8\0"
"Envisage\0"
"Euros [drifteuros]\0"
"Euros [Euros]\0"
"Feltzer\0"
"Flash GT\0"
"Furore GT\0"
"Fusilade\0"
"Futo [driftfuto2]\0"
"Futo [futo]\0"
"Futo GTX [driftfuto]\0"
"Futo GTX [futo2]\0"
"Future Shock ZR380\0"
"GB200\0"
"Go Go Monkey Blista\0"
"Growler\0"
"Hotring Everon\0"
"Hotring Hellfire\0"
"Hotring Sabre\0"
"Imorgon\0"
"Issi Sport\0"
"Itali GTO\0"
"Itali GTO Stinger TT\0"
"Itali RSX\0"
"Jester\0"
"Jester (Racecar)\0"
"Jester Classic [jester3]\0"
"Jester RR [driftjester]\0"
"Jester RR [jester4]\0"
"Jester RR Widebody\0"
"Jugular\0"
"Khamelion\0"
"Komoda\0"
"Kuruma\0"
"Kuruma (Armored)\0"
"La Coureuse\0"
"Locust\0"
"Lynx\0"
"Massacro\0"
"Massacro (Racecar)\0"
"Neo\0"
"Neon\0"
"Nightmare ZR380\0"
"Niobe\0"
"Omnis\0"
"Omnis e-GT\0"
"Panthere\0"
"Paragon R\0"
"Paragon R (Armored)\0"
"Paragon S\0"
"Pariah\0"
"Penumbra\0"
"Penumbra FF\0"
"Raiden\0"
"Rapid GT [RapidGT]\0"
"Rapid GT [RapidGT2]\0"
"Rapid GT X\0"
"Raptor\0"
"Remus [driftremus]\0"
"Remus [remus]\0"
"Revolter\0"
"RT3000 [driftrt3000]\0"
"RT3000 [rt3000]\0"
"Ruston\0"
"S95\0"
"Schafter LWB\0"
"Schafter V12\0"
"Schlagen GT\0"
"Schwartzer\0"
"Sentinel [sentinel3]\0"
"Sentinel Classic Widebody [driftsentinel]\0"
"Sentinel Classic Widebody [sentinel4]\0"
"Sentinel GTS\0"
"Seven-70\0"
"SM722\0"
"Specter\0"
"Specter Custom\0"
"Sprunk Buffalo\0"
"Streiter\0"
"Sugoi\0"
"Sultan\0"
"Sultan Classic\0"
"Sultan RS Classic\0"
"Surano\0"
"Tropos Rallye\0"
"V-STR\0"
"Vectre\0"
"Verlierer\0"
"Veto Classic\0"
"Veto Modern\0"
"ZR350 [driftzr350]\0"
"ZR350 [zr350]\0"
"Apocalypse Dominator\0"
"Apocalypse Impaler\0"
"Apocalypse Imperator\0"
"Apocalypse Slamvan\0"
"Arbiter GT\0"
"Beater Dukes\0"
"Blade\0"
"Brigham\0"
"Broadway\0"
"Buccaneer\0"
"Buccaneer Custom\0"
"Buffalo EVX\0"
"Buffalo STX\0"
"Burger Shot Stallion\0"
"Chino\0"
"Chino Custom\0"
"Clique\0"
"Clique Wagon\0"
"Coquette BlackFin\0"
"Deviant\0"
"Dominator\0"
"Dominator ASP\0"
"Dominator FX [dominator10]\0"
"Dominator FX [driftdominator10]\0"
"Dominator GT [dominator9]\0"
"Dominator GT [driftdominator9]\0"
"Dominator GTT\0"
"Dominator GTX\0"
"Drift Yosemite [driftyosemite]\0"
"Drift Yosemite [yosemite2]\0"
"Duke O'Death\0"
"Dukes\0"
"Ellie\0"
"Eudora\0"
"Faction\0"
"Faction Custom 1\0"
"Faction Custom Donk\0"
"Future Shock Dominator\0"
"Future Shock Impaler\0"
"Future Shock Imperator\0"
"Future Shock Slamvan\0"
"Gauntlet\0"
"Gauntlet Classic\0"
"Gauntlet Classic Custom\0"
"Gauntlet Hellfire [driftgauntlet4]\0"
"Gauntlet Hellfire [gauntlet4]\0"
"Greenwood\0"
"Hermes\0"
"Hotknife\0"
"Hustler\0"
"Impaler\0"
"Impaler LX\0"
"Impaler SZ\0"
"Lost Slamvan\0"
"Lurcher\0"
"Manana Custom\0"
"Moonbeam\0"
"Moonbeam Custom\0"
"Nightmare Dominator\0"
"Nightmare Impaler\0"
"Nightmare Imperator\0"
"Nightmare Slamvan\0"
"Nightshade\0"
"Peyote Gasser\0"
"Phoenix\0"
"Picador\0"
"Pisswasser Dominator\0"
"Rat-Loader\0"
"Rat-Truck\0"
"Redwood Gauntlet\0"
"Ruiner [ruiner]\0"
"Ruiner [ruiner3]\0"
"Ruiner 2000\0"
"Ruiner ZZ-8\0"
"Sabre Turbo\0"
"Sabre Turbo Custom\0"
"Slamvan\0"
"Slamvan Custom\0"
"Stallion\0"
"Tahoma Coupe\0"
"Tampa\0"
"Tampa GT\0"
"Tulip\0"
"Tulip M-100\0"
"Vamos\0"
"Vigero\0"
"Vigero ZX\0"
"Vigero ZX Convertible\0"
"Virgo\0"
"Virgo Classic\0"
"Virgo Classic Custom\0"
"Voodoo\0"
"Voodoo Custom\0"
"Weaponized Tampa\0"
"Weevil Custom\0"
"Yosemite\0"
"190z\0"
"Ardent\0"
"Astrale\0"
"Casco\0"
"Cheburek [cheburek]\0"
"Cheburek [driftcheburek]\0"
"Cheetah Classic\0"
"Coquette Classic\0"
"Coquette D1\0"
"Deluxo\0"
"Dynasty\0"
"Fagaloa\0"
"Feltzer Classic\0"
"Franken Stange\0"
"GT500\0"
"GT750\0"
"Infernus Classic\0"
"Itali Classic\0"
"JB 700\0"
"JB 700W\0"
"Jester Classic [driftjester3]\0"
"LSCM Cheetah Classic\0"
"Mamba\0"
"Manana\0"
"Michelli GT\0"
"Monroe\0"
"Nebula Turbo [driftnebula]\0"
"Nebula Turbo [nebula]\0"
"Peyote\0"
"Peyote Custom\0"
"Pigalle\0"
"Rapid GT Classic\0"
"Retinue\0"
"Retinue Mk II\0"
"Roosevelt\0"
"Roosevelt Valor\0"
"Savestra\0"
"Stinger\0"
"Stinger GT\0"
"Stromberg\0"
"Swinger\0"
"Toreador\0"
"Torero\0"
"Tornado [tornado]\0"
"Tornado [tornado2]\0"
"Tornado [tornado3]\0"
"Tornado [tornado4]\0"
"Tornado Custom\0"
"Tornado Rat Rod\0"
"Turismo Classic\0"
"Uranus LozSpeed\0"
"Viseris\0"
"Z-Type\0"
"Zion Classic\0"
"BR8\0"
"DR1\0"
"PR4\0"
"R88\0"
"Cognoscenti Cabrio\0"
"Euros X32\0"
"Exemplar\0"
"F620\0"
"Felon\0"
"Felon GT\0"
"FR36 [driftfr36]\0"
"FR36 [fr36]\0"
"Jackal\0"
"Kanjo SJ\0"
"Oracle\0"
"Oracle XS\0"
"Postlude\0"
"Previon\0"
"Sentinel [sentinel2]\0"
"Sentinel XS [driftsentinel2]\0"
"Sentinel XS [sentinel]\0"
"Windsor\0"
"Windsor Drop\0"
"Zion\0"
"Zion Cabrio\0"
"Asea [asea]\0"
"Asea [asea2]\0"
"Asterope\0"
"Asterope GZ\0"
"Chavos V6 [chavosv6]\0"
"Chavos V6 [driftchavosv6]\0"
"Cinquemila\0"
"Cognoscenti\0"
"Cognoscenti (Armored)\0"
"Cognoscenti 55\0"
"Cognoscenti 55 (Armored)\0"
"Deity\0"
"Emperor [emperor]\0"
"Emperor [Emperor2]\0"
"Emperor [emperor3]\0"
"Fugitive\0"
"Glendale\0"
"Glendale Custom\0"
"Hardy [drifthardy]\0"
"Hardy [hardy]\0"
"Ingot\0"
"Intruder\0"
"Minimus\0"
"Premier\0"
"Primo\0"
"Primo Custom\0"
"Regina\0"
"Rhinehart\0"
"Romero Hearse\0"
"Schafter\0"
"Schafter LWB (Armored)\0"
"Schafter V12 (Armored)\0"
"Sentinel XS4\0"
"Stafford\0"
"Stanier\0"
"Stratum\0"
"Stretch\0"
"Super Diamond\0"
"Surge\0"
"Tailgater\0"
"Tailgater S\0"
"Turreted Limo\0"
"Vorschlaghammer [driftvorschlag]\0"
"Vorschlaghammer [vorschlaghammer]\0"
"Warrener\0"
"Warrener HKR\0"
"Washington\0"
"Apocalypse Issi\0"
"Asbo\0"
"Blista\0"
"Blista Kanjo\0"
"Brioso 300\0"
"Brioso 300 Widebody\0"
"Brioso R/A\0"
"Club\0"
"Dilettante [dilettante]\0"
"Dilettante [dilettante2]\0"
"Future Shock Issi\0"
"Issi\0"
"Issi Classic\0"
"Nightmare Issi\0"
"Panto\0"
"Prairie\0"
"Rhapsody\0"
"Weevil\0"
"Aleutian\0"
"Astron\0"
"Astron Custom\0"
"Baller [Baller]\0"
"Baller [baller2]\0"
"Baller LE\0"
"Baller LE (Armored)\0"
"Baller LE LWB\0"
"Baller LE LWB (Armored)\0"
"Baller ST\0"
"Baller ST-D\0"
"BeeJay XL\0"
"Castigator\0"
"Cavalcade [cavalcade]\0"
"Cavalcade [cavalcade2]\0"
"Cavalcade XL\0"
"Contender\0"
"Dorado\0"
"Dubsta [dubsta]\0"
"Dubsta [dubsta2]\0"
"Everon RS\0"
"FQ 2\0"
"Granger\0"
"Granger 3600LX\0"
"Gresley\0"
"Habanero\0"
"Huntley S\0"
"I-Wagen\0"
"Issi Rally\0"
"Jubilee\0"
"Landstalker\0"
"Landstalker XL\0"
"Mesa [MESA]\0"
"Mesa [mesa2]\0"
"Novak\0"
"Patriot\0"
"Patriot Stretch\0"
"Radius\0"
"Rebla GTS\0"
"Rocoto\0"
"Seminole\0"
"Seminole Frontier\0"
"Serrano\0"
"Squaddie\0"
"Toros\0"
"Vivanite [vivanite]\0"
"Woodlander\0"
"XLS\0"
"XLS (Armored)\0"
"Apocalypse Bruiser\0"
"Apocalypse Brutus\0"
"Apocalypse Sasquatch\0"
"Bifta\0"
"Blazer\0"
"Blazer Aqua\0"
"Blazer Lifeguard\0"
"Bodhi\0"
"Boor\0"
"Brawler\0"
"Caracara\0"
"Caracara 4x4\0"
"Desert Raid\0"
"Draugur\0"
"Drift Walton L35\0"
"Dubsta 6x6\0"
"Dune Buggy\0"
"Dune FAV\0"
"Duneloader\0"
"Everon\0"
"Firebolt ASP\0"
"Freecrawler\0"
"Future Shock Bruiser\0"
"Future Shock Brutus\0"
"Future Shock Sasquatch\0"
"Hellion\0"
"Hot Rod Blazer\0"
"Injection\0"
"Insurgent\0"
"Insurgent Pick-Up\0"
"Insurgent Pick-Up Custom\0"
"Kalahari\0"
"Kamacho\0"
"Marshall\0"
"Menacer\0"
"Mesa [MESA3]\0"
"Monster\0"
"MonstroCiti\0"
"Nightmare Bruiser\0"
"Nightmare Brutus\0"
"Nightmare Sasquatch\0"
"Nightshark\0"
"Outlaw\0"
"Patriot Mil-Spec\0"
"Ramp Buggy [dune4]\0"
"Ramp Buggy [dune5]\0"
"Rancher XL [RancherXL]\0"
"Rancher XL [rancherxl2]\0"
"Ratel\0"
"RC Bandito\0"
"Rebel\0"
"Riata\0"
"Rusty Rebel\0"
"Sandking SWB\0"
"Sandking XL\0"
"Space Docker\0"
"Street Blazer\0"
"Technical\0"
"Technical Aqua\0"
"Technical Custom\0"
"Terminus\0"
"Trophy Truck\0"
"Vagrant\0"
"Verus\0"
"Walton L35\0"
"Walton L35 Stock\0"
"Winky\0"
"Yosemite 1500\0"
"Yosemite Rancher\0"
"Zhaba\0"
"Akuma\0"
"Apocalypse Deathbike\0"
"Avarus\0"
"Bagger\0"
"Bati 801\0"
"Bati 801RR\0"
"BF400\0"
"Carbon RS\0"
"Chimera\0"
"Cliffhanger\0"
"Daemon\0"
"Daemon Custom\0"
"Defiler\0"
"Diabolus\0"
"Diabolus Custom\0"
"Double-T\0"
"Enduro\0"
"Esskey\0"
"Faggio\0"
"Faggio Mod\0"
"Faggio Sport\0"
"FCR 1000\0"
"FCR 1000 Custom\0"
"Future Shock Deathbike\0"
"Gargoyle\0"
"Hakuchou\0"
"Hakuchou Drag\0"
"Hexer\0"
"Innovation\0"
"Lectro\0"
"Manchez\0"
"Manchez Scout\0"
"Manchez Scout C\0"
"Nemesis\0"
"Nightblade\0"
"Nightmare Deathbike\0"
"Oppressor\0"
"Oppressor Mk II\0"
"PCJ 600\0"
"Pizza Boy\0"
"Powersurge\0"
"Rampant Rocket\0"
"Rat Bike\0"
"Reever\0"
"Ruffian\0"
"Sanchez\0"
"Sanchez (livery)\0"
"Sanctus\0"
"Shinobi\0"
"Shotaro\0"
"Sovereign\0"
"Stryder\0"
"Thrust\0"
"Vader\0"
"Vindicator\0"
"Vortex\0"
"Wolfsbane\0"
"Zombie Bobber\0"
"Zombie Chopper\0"
"BMX\0"
"Cruiser\0"
"Endurex Race Bike\0"
"Fixter\0"
"Inductor\0"
"Junk Energy Inductor\0"
"Scorcher\0"
"Tri-Cycles Race Bike\0"
"Whippet Race Bike\0"
"Armored Boxville\0"
"Bison [bison]\0"
"Bison [Bison2]\0"
"Bison [Bison3]\0"
"Bobcat XL\0"
"Boxville (LSDS)\0"
"Boxville [boxville]\0"
"Boxville [boxville2]\0"
"Boxville [boxville3]\0"
"Boxville [boxville4]\0"
"Bugstars Burrito\0"
"Burrito [Burrito]\0"
"Burrito [burrito3]\0"
"Burrito [Burrito4]\0"
"Burrito [burrito5]\0"
"Camper\0"
"Clown Van\0"
"Gang Burrito [gburrito]\0"
"Gang Burrito [gburrito2]\0"
"Journey\0"
"Journey II\0"
"Minivan\0"
"Minivan Custom\0"
"Paradise\0"
"Pony [pony]\0"
"Pony [pony2]\0"
"Rumpo [rumpo]\0"
"Rumpo [rumpo2]\0"
"Rumpo Custom\0"
"Speedo\0"
"Speedo Custom [speedo4]\0"
"Speedo Custom [speedo5]\0"
"Surfer [SURFER]\0"
"Surfer [Surfer2]\0"
"Surfer Custom\0"
"Taco Van\0"
"Youga\0"
"Youga Classic\0"
"Youga Classic 4x4\0"
"Youga Custom [youga4]\0"
"Youga Custom [youga5]\0"
"Custom Flatbed\0"
"Cutter\0"
"Dock Handler\0"
"Dozer\0"
"Dump\0"
"Flatbed\0"
"Guardian\0"
"Mixer [Mixer]\0"
"Mixer [Mixer2]\0"
"Rubble\0"
"Tipper [TipTruck]\0"
"Tipper [TipTruck2]\0"
"Airtug\0"
"Caddy [caddy]\0"
"Caddy [Caddy2]\0"
"Caddy [caddy3]\0"
"Docktug\0"
"Fieldmaster [tractor2]\0"
"Fieldmaster [tractor3]\0"
"Forklift\0"
"Keitora [driftkeitora]\0"
"Keitora [keitora]\0"
"Lawn Mower\0"
"Ripley\0"
"Sadler [Sadler]\0"
"Sadler [sadler2]\0"
"Scrap Truck\0"
"Slamtruck\0"
"Tow Truck [TOWTRUCK]\0"
"Tow Truck [Towtruck2]\0"
"Tow Truck [towtruck3]\0"
"Tow Truck [towtruck4]\0"
"Tractor\0"
"Utility Truck [utillitruck]\0"
"Utility Truck [utillitruck2]\0"
"Utility Truck [Utillitruck3]\0"
"Airport Bus\0"
"Brickade\0"
"Brickade 6x6\0"
"Bus\0"
"Dashound\0"
"Dune\0"
"Festival Bus\0"
"Rental Shuttle Bus\0"
"Taxi\0"
"Tour Bus\0"
"Trashmaster [Trash]\0"
"Trashmaster [trash2]\0"
"Vivanite [vivanite2]\0"
"Wastelander\0"
"Ambulance\0"
"Buffalo Cruiser\0"
"Buffalo STX Pursuit\0"
"Burrito (Bail Enforcement)\0"
"Caracara Pursuit\0"
"Coquette D10 Pursuit\0"
"Dominator FX Interceptor\0"
"Dorado Cruiser\0"
"FIB [FBI]\0"
"FIB [FBI2]\0"
"Fire Truck\0"
"Gauntlet Interceptor\0"
"Greenwood Cruiser\0"
"Impaler LX Cruiser\0"
"Impaler SZ Cruiser\0"
"Lifeguard\0"
"Outreach Faction\0"
"Park Ranger\0"
"Police Bike [policeb]\0"
"Police Bike [policeb2]\0"
"Police Cruiser [police]\0"
"Police Cruiser [police2]\0"
"Police Cruiser [police3]\0"
"Police Prison Bus\0"
"Police Rancher\0"
"Police Riot\0"
"Police Roadcruiser\0"
"Police Transporter\0"
"RCV\0"
"Sheriff Cruiser\0"
"Sheriff SUV\0"
"Stanier LE Cruiser\0"
"Terminus Patrol\0"
"Unmarked Cruiser\0"
"APC\0"
"Apocalypse Scarab\0"
"Barracks [BARRACKS]\0"
"Barracks [BARRACKS3]\0"
"Barracks Semi\0"
"Barrage\0"
"Chernobog\0"
"Crusader\0"
"Future Shock Scarab\0"
"Half-track\0"
"Invade and Persuade Tank\0"
"Nightmare Scarab\0"
"Rhino Tank\0"
"Thruster\0"
"TM-02 Khanjali\0"
"Vetir\0"
"Apocalypse Cerberus\0"
"Benson\0"
"Benson (Cluckin' Bell)\0"
"Biff\0"
"Bobcat Security Stockade\0"
"Future Shock Cerberus\0"
"Hauler\0"
"Hauler Custom\0"
"Mule [Mule]\0"
"Mule [Mule2]\0"
"Mule [Mule3]\0"
"Mule [mule5]\0"
"Mule Custom\0"
"Nightmare Cerberus\0"
"Packer\0"
"Phantom [Phantom]\0"
"Phantom [Phantom4]\0"
"Phantom Custom\0"
"Phantom Wedge\0"
"Pounder\0"
"Pounder Custom\0"
"Stockade [stockade]\0"
"Stockade [stockade3]\0"
"Terrorbyte\0"
"Avisa\0"
"Dinghy [Dinghy]\0"
"Dinghy [dinghy2]\0"
"Dinghy [dinghy3]\0"
"Dinghy [dinghy4]\0"
"Jetmax\0"
"Kosatka\0"
"Kraken\0"
"Kurtz 31 Patrol Boat\0"
"Longfin\0"
"Marquis\0"
"Police Predator\0"
"Seashark [seashark]\0"
"Seashark [seashark2]\0"
"Seashark [seashark3]\0"
"Speeder [speeder]\0"
"Speeder [speeder2]\0"
"Squalo\0"
"Submersible\0"
"Suntrap\0"
"Toro [toro]\0"
"Toro [toro2]\0"
"Tropic [tropic]\0"
"Tropic [tropic2]\0"
"Tug\0"
"Weaponized Dinghy\0"
"Akula\0"
"Annihilator\0"
"Annihilator Stealth\0"
"Buzzard\0"
"Buzzard Attack Chopper\0"
"Cargobob [Cargobob]\0"
"Cargobob [cargobob2]\0"
"Cargobob [Cargobob3]\0"
"Cargobob [Cargobob4]\0"
"Conada\0"
"DH-7 Iron Mule\0"
"FH-1 Hunter\0"
"Frogger [Frogger]\0"
"Frogger [frogger2]\0"
"Havok\0"
"Higgins Helitours Maverick\0"
"Maverick\0"
"Police Maverick\0"
"Savage\0"
"Sea Sparrow\0"
"Skylift\0"
"Sparrow [seasparrow2]\0"
"Sparrow [seasparrow3]\0"
"SuperVolito\0"
"SuperVolito Carbon\0"
"Swift\0"
"Swift Deluxe\0"
"Valkyrie\0"
"Valkyrie MOD.0\0"
"Volatus\0"
"Weaponized Conada\0"
"Alpha-Z1\0"
"Atomic Blimp\0"
"Avenger [avenger]\0"
"Avenger [avenger2]\0"
"Avenger [avenger3]\0"
"Avenger [avenger4]\0"
"B-11 Strikeforce\0"
"Besra\0"
"Blimp\0"
"Cargo Plane [cargoplane]\0"
"Cargo Plane [cargoplane2]\0"
"Cuban 800\0"
"Dodo\0"
"Duster\0"
"Duster 300-H\0"
"F-160 Raiju\0"
"Howard NX-25\0"
"Hydra\0"
"Jet\0"
"LF-22 Starling\0"
"Luxor\0"
"Luxor Deluxe\0"
"Mallard\0"
"Mammatus\0"
"Miljet\0"
"Mogul\0"
"Nimbus\0"
"P-45 Nokota\0"
"P-996 LAZER\0"
"Pyro\0"
"RM-10 Bombushka\0"
"RO-86 Alkonost\0"
"Rogue\0"
"Seabreeze\0"
"Shamal\0"
"Streamer216\0"
"Titan\0"
"Titan 250 D\0"
"Tula\0"
"Ultralight\0"
"V-65 Molotok\0"
"Velum\0"
"Velum 5-Seater\0"
"Vestra\0"
"Volatol\0"
"Xero Blimp\0";
static const struct { u32 model; unsigned short label; u8 category; } vehicle_catalogue[] = {
{2465164804u,0,7},
{3078201489u,4,7},
{3981782132u,10,7},
{633712403u,18,7},
{2598821281u,31,7},
{3379732821u,38,7},
{2983812512u,47,7},
{1392481335u,55,7},
{386089410u,63,7},
{1591739866u,74,7},
{1323778901u,88,7},
{1748565021u,95,7},
{3003014393u,105,7},
{2174267100u,115,7},
{819197656u,126,7},
{1426219628u,131,7},
{3287642921u,135,7},
{960812448u,144,7},
{1234311532u,150,7},
{2850852987u,154,7},
{418536135u,160,7},
{2246633323u,169,7},
{3812247419u,179,7},
{3630826055u,196,7},
{4284049613u,204,7},
{3356898886u,209,7},
{1034187331u,215,7},
{1093792632u,220,7},
{1987142870u,232,7},
{2536829930u,239,7},
{4071505793u,250,7},
{3062131285u,262,7},
{234062309u,268,7},
{989294410u,275,7},
{3970348707u,289,7},
{1352136073u,295,7},
{3656405053u,299,7},
{3999278268u,308,7},
{687627128u,318,7},
{1663218586u,325,7},
{3160260734u,329,7},
{272929391u,336,7},
{1031562256u,345,7},
{1044193113u,354,7},
{2936769864u,360,7},
{4129572538u,366,7},
{4171974011u,376,7},
{408192225u,392,7},
{3918533058u,402,7},
{2067820283u,409,7},
{338562499u,415,7},
{1939284556u,421,7},
{3052358707u,428,7},
{669204833u,438,7},
{3296789504u,445,7},
{2672523198u,453,7},
{956849991u,460,7},
{2515968713u,477,7},
{2123327359u,485,7},
{917809321u,495,7},
{655665811u,501,7},
{2891838741u,506,7},
{3612858749u,515,7},
{3400983137u,524,6},
{274946574u,528,6},
{1076201208u,541,6},
{686471183u,546,6},
{1032823388u,557,6},
{2833484545u,560,6},
{767087018u,570,6},
{540101442u,576,6},
{3253274834u,593,6},
{3634959571u,601,6},
{1274868363u,613,6},
{1039032026u,624,6},
{3990165190u,639,6},
{736902334u,647,6},
{3101054893u,657,6},
{2072687711u,668,6},
{3249425686u,681,6},
{2272483501u,687,6},
{2568944644u,706,6},
{1141395928u,715,6},
{1561920505u,731,6},
{661493923u,744,6},
{108773431u,753,6},
{2566281822u,762,6},
{127317925u,775,6},
{3540279623u,787,6},
{1755697647u,795,6},
{258105345u,811,6},
{2598648200u,832,6},
{3223586949u,857,6},
{196747873u,878,6},
{3728579874u,897,6},
{1121330119u,907,6},
{821121576u,916,6},
{2038480341u,935,6},
{2299640309u,949,6},
{3035832600u,957,6},
{3205927392u,966,6},
{499169875u,976,6},
{3005741670u,985,6},
{2016857647u,1003,6},
{4113404654u,1015,6},
{2787736776u,1036,6},
{3188846534u,1053,6},
{1909189272u,1072,6},
{3703315515u,1078,6},
{1304459735u,1098,6},
{4163619118u,1106,6},
{1336514315u,1121,6},
{1115909093u,1138,6},
{3162245632u,1152,6},
{1854776567u,1160,6},
{3963499524u,1171,6},
{1447690049u,1181,6},
{3145241962u,1202,6},
{2997294755u,1212,6},
{3188613414u,1219,6},
{4080061290u,1236,6},
{2531693357u,1261,6},
{2712905841u,1285,6},
{1484920335u,1305,6},
{4086055493u,1324,6},
{544021352u,1332,6},
{3460613305u,1342,6},
{2922118804u,1349,6},
{410882957u,1356,6},
{610429990u,1373,6},
{3353694737u,1385,6},
{482197771u,1392,6},
{4152024626u,1397,6},
{3663206819u,1406,6},
{2674840994u,1425,6},
{2445973230u,1429,6},
{2816263004u,1434,6},
{1881415402u,1450,6},
{3517794615u,1456,6},
{3789743831u,1462,6},
{2100457220u,1473,6},
{3847255899u,1482,6},
{1416466158u,1492,6},
{3348919626u,1512,6},
{867799010u,1522,6},
{3917501776u,1529,6},
{3663644634u,1538,6},
{2765724541u,1550,6},
{2360515092u,1557,6},
{1737773231u,1576,6},
{1761301369u,1596,6},
{3620039993u,1607,6},
{2670883828u,1614,6},
{1377217886u,1633,6},
{3884762073u,1647,6},
{1730644782u,1656,6},
{3842363289u,1677,6},
{719660200u,1693,6},
{1133471123u,1700,6},
{1489967196u,1704,6},
{2809443750u,1717,6},
{3787471536u,1730,6},
{3548084598u,1742,6},
{1104234922u,1753,6},
{3308310822u,1774,6},
{2938086457u,1816,6},
{2709293299u,1854,6},
{2537130571u,1867,6},
{775514032u,1876,6},
{1886268224u,1882,6},
{1074745671u,1890,6},
{237764926u,1905,6},
{1741861769u,1920,6},
{987469656u,1929,6},
{970598228u,1935,6},
{872704284u,1942,6},
{4003946083u,1957,6},
{384071873u,1975,6},
{1887331236u,1982,6},
{1456336509u,1996,6},
{2754593701u,2002,6},
{1102544804u,2009,6},
{3437611258u,2019,6},
{2802050217u,2032,6},
{1923534526u,2044,6},
{2436313176u,2063,6},
{3606777648u,2077,4},
{1009171724u,2098,4},
{444994115u,2117,4},
{2233918197u,2138,4},
{1549009676u,2157,4},
{2134119907u,2168,4},
{3089165662u,2181,4},
{3640468689u,2187,4},
{2361724968u,2195,4},
{3612755468u,2204,4},
{3281516360u,2214,4},
{165968051u,2231,4},
{3675036420u,2243,4},
{3893323758u,2255,4},
{349605904u,2276,4},
{2933279331u,2282,4},
{2728360112u,2295,4},
{3315674721u,2302,4},
{784565758u,2315,4},
{1279262537u,2333,4},
{80636076u,2341,4},
{426742808u,2351,4},
{1579902654u,2365,4},
{3355365473u,2392,4},
{3853757601u,2424,4},
{3439117103u,2450,4},
{736672010u,2481,4},
{3308022675u,2495,4},
{2613313775u,2509,4},
{1693751655u,2540,4},
{3968823444u,2567,4},
{723973206u,2580,4},
{3027423925u,2586,4},
{3045179290u,2592,4},
{2175389151u,2599,4},
{2504420315u,2607,4},
{2255212070u,2624,4},
{2919906639u,2644,4},
{2370166601u,2667,4},
{1637620610u,2688,4},
{373261600u,2711,4},
{2494797253u,2732,4},
{722226637u,2741,4},
{2172320429u,2758,4},
{3933619103u,2782,4},
{1934384720u,2817,4},
{40817712u,2847,4},
{15219735u,2857,4},
{37348240u,2864,4},
{600450546u,2873,4},
{2198276962u,2881,4},
{4116524922u,2889,4},
{3816328113u,2900,4},
{833469436u,2911,4},
{2068293287u,2924,4},
{1717532765u,2932,4},
{525509695u,2946,4},
{1896491931u,2955,4},
{3001042683u,2971,4},
{2550461639u,2991,4},
{3539435063u,3009,4},
{1742022738u,3029,4},
{2351681756u,3047,4},
{2490551588u,3058,4},
{2199527893u,3072,4},
{1507916787u,3080,4},
{3379262425u,3088,4},
{3627815886u,3109,4},
{3705788919u,3120,4},
{349315417u,3130,4},
{4067225593u,3147,4},
{777714999u,3163,4},
{941494461u,3180,4},
{1706945532u,3192,4},
{2609945748u,3204,4},
{223258115u,3216,4},
{729783779u,3235,4},
{1119641113u,3243,4},
{1923400478u,3258,4},
{3833117047u,3267,4},
{972671128u,3280,4},
{2786546796u,3286,4},
{1456744817u,3295,4},
{268758436u,3301,4},
{4245851645u,3313,4},
{3469130167u,3319,4},
{2536587772u,3326,4},
{372621319u,3336,4},
{3796912450u,3358,4},
{16646064u,3364,4},
{3395457658u,3378,4},
{523724515u,3399,4},
{2006667053u,3406,4},
{3084515313u,3420,4},
{3300595976u,3437,4},
{1871995513u,3451,4},
{838982985u,3460,5},
{159274291u,3465,5},
{1596736441u,3472,5},
{941800958u,3480,5},
{3306466016u,3486,5},
{2828274931u,3506,5},
{223240013u,3531,5},
{1011753235u,3547,5},
{2336538363u,3564,5},
{1483171323u,3576,5},
{310284501u,3583,5},
{1617472902u,3591,5},
{2728226064u,3599,5},
{3463132580u,3615,5},
{2215179066u,3630,5},
{1380582820u,3636,5},
{2889029532u,3642,5},
{893780296u,3659,5},
{1051415893u,3673,5},
{394110044u,3680,5},
{3932276298u,3688,5},
{471399650u,3718,5},
{2634021974u,3739,5},
{2170765704u,3745,5},
{1046206681u,3752,5},
{3861591579u,3764,5},
{1690421418u,3771,5},
{3412338231u,3798,5},
{1830407356u,3820,5},
{1107404867u,3827,5},
{1078682497u,3841,5},
{2049897956u,3849,5},
{1841130506u,3866,5},
{2031587082u,3874,5},
{117401876u,3888,5},
{3692679425u,3898,5},
{903794909u,3914,5},
{1545842587u,3923,5},
{2196019706u,3931,5},
{886810209u,3942,5},
{500482303u,3952,5},
{1455990255u,3960,5},
{1504306544u,3969,5},
{464687292u,3976,5},
{1531094468u,3994,5},
{1762279763u,4013,5},
{2261744861u,4032,5},
{2497353967u,4051,5},
{2736567667u,4066,5},
{3312836369u,4082,5},
{1534326199u,4098,5},
{3903371924u,4114,5},
{758895617u,4122,5},
{1862507111u,4129,5},
{1492612435u,4142,22},
{1181339704u,4146,22},
{340154634u,4150,22},
{2334210311u,4154,22},
{330661258u,4158,3},
{3295372994u,4177,3},
{4289813342u,4187,3},
{3703357000u,4196,3},
{3903372712u,4201,3},
{4205676014u,4207,3},
{2815031719u,4216,3},
{3829141989u,4233,3},
{3670438162u,4245,3},
{4230891418u,4252,3},
{3783366066u,4261,3},
{1348744438u,4268,3},
{4000288633u,4278,3},
{1416471345u,4287,3},
{873639469u,4295,3},
{3288768346u,4316,3},
{1349725314u,4345,3},
{1581459400u,4368,3},
{2364918497u,4376,3},
{3172678083u,4389,3},
{3101863448u,4394,3},
{2485144969u,4406,1},
{2487343317u,4418,1},
{2391954683u,4431,1},
{3553846961u,4440,1},
{1992041063u,4452,1},
{457814204u,4473,1},
{2767531027u,4499,1},
{2264796000u,4510,1},
{3690124666u,4522,1},
{906642318u,4544,1},
{704435172u,4559,1},
{1532171089u,4584,1},
{3609690755u,4590,1},
{2411965148u,4608,1},
{3053254478u,4627,1},
{1909141499u,4646,1},
{75131841u,4655,1},
{3381377750u,4664,1},
{3893408850u,4680,1},
{1580292663u,4699,1},
{3005245074u,4713,1},
{886934177u,4719,1},
{3193860278u,4728,1},
{2411098011u,4736,1},
{3144368207u,4744,1},
{2254540506u,4750,1},
{4280472072u,4763,1},
{2439462158u,4770,1},
{627094268u,4780,1},
{3039514899u,4794,1},
{1922255844u,4803,1},
{3406724313u,4826,1},
{3936328504u,4849,1},
{321186144u,4862,1},
{2817386317u,4871,1},
{1723137093u,4879,1},
{2333339779u,4887,1},
{1123216662u,4895,1},
{2400073108u,4909,1},
{3286105550u,4915,1},
{3050505892u,4925,1},
{4180339789u,4937,1},
{4151380270u,4951,1},
{3054795149u,4984,1},
{1373123368u,5018,1},
{579912970u,5027,1},
{1777363799u,5040,1},
{628003514u,5051,0},
{1118611807u,5067,0},
{3950024287u,5072,0},
{409049982u,5079,0},
{1429622905u,5092,0},
{15214558u,5103,0},
{1549126457u,5123,0},
{2196012677u,5134,0},
{3164157193u,5139,0},
{1682114128u,5163,0},
{1537277726u,5188,0},
{3117103977u,5206,0},
{931280609u,5211,0},
{1239571361u,5224,0},
{3863274624u,5239,0},
{2844316578u,5245,0},
{841808271u,5253,0},
{1644055914u,5262,0},
{4256087847u,5269,2},
{629969764u,5278,2},
{2803699023u,5285,2},
{3486135912u,5299,2},
{142944341u,5315,2},
{1878062887u,5332,2},
{470404958u,5342,2},
{634118882u,5362,2},
{666166960u,5376,2},
{359875117u,5400,2},
{3431608412u,5410,2},
{850565707u,5422,2},
{1307736079u,5432,2},
{2006918058u,5443,2},
{3505073125u,5465,2},
{3265236814u,5488,2},
{683047626u,5501,2},
{3526923154u,5511,2},
{1177543287u,5518,2},
{3900892662u,5534,2},
{554408685u,5551,2},
{3157435195u,5561,2},
{2519238556u,5566,2},
{4033620423u,5574,2},
{2751205197u,5589,2},
{884422927u,5597,2},
{486987393u,5606,2},
{662793086u,5616,2},
{1550581940u,5624,2},
{461465043u,5635,2},
{1269098716u,5643,2},
{3456868130u,5655,2},
{914654722u,5670,2},
{3546958660u,5682,2},
{2465530446u,5695,2},
{3486509883u,5701,2},
{3874056184u,5709,2},
{2643899483u,5725,2},
{83136452u,5732,2},
{2136773105u,5742,2},
{1221512915u,5749,2},
{2484160806u,5758,2},
{1337041428u,5776,2},
{4192631813u,5784,2},
{3126015148u,5793,2},
{2922168362u,5799,2},
{1966698497u,5819,2},
{1203490606u,5830,2},
{3862958888u,5834,2},
{668439077u,5848,9},
{2139203625u,5867,9},
{1721676810u,5885,9},
{3945366167u,5906,9},
{2166734073u,5912,9},
{2704629607u,5919,9},
{4246935337u,5931,9},
{2859047862u,5948,9},
{996383885u,5954,9},
{2815302597u,5959,9},
{1254014755u,5967,9},
{2945871676u,5976,9},
{3631668194u,5989,9},
{3526730918u,6001,9},
{2312533665u,6009,9},
{3057713523u,6026,9},
{2633113103u,6037,9},
{1897744184u,6048,9},
{1770332643u,6057,9},
{2538945576u,6068,9},
{3321950518u,6075,9},
{4240635011u,6088,9},
{2600885406u,6100,9},
{2403970600u,6121,9},
{840387324u,6141,9},
{3932816511u,6164,9},
{3025077634u,6172,9},
{1126868326u,6187,9},
{2071877360u,6197,9},
{2434067162u,6207,9},
{2370534026u,6225,9},
{92612664u,6250,9},
{4173521127u,6259,9},
{1233534620u,6267,9},
{2044532910u,6276,9},
{2230595153u,6284,9},
{3449006043u,6297,9},
{802856453u,6305,9},
{2252616474u,6317,9},
{2038858402u,6335,9},
{3579220348u,6352,9},
{433954513u,6372,9},
{408825843u,6383,9},
{3624880708u,6390,9},
{3467805257u,6407,9},
{3982671785u,6426,9},
{1645267888u,6445,9},
{1933662059u,6468,9},
{3758861739u,6492,9},
{4008920556u,6498,9},
{2249373259u,6509,9},
{2762269779u,6515,9},
{3087195462u,6521,9},
{989381445u,6533,9},
{3105951696u,6546,9},
{534258863u,6558,9},
{3854198872u,6571,9},
{2198148358u,6585,9},
{1180875963u,6595,9},
{1356124575u,6610,9},
{167522317u,6627,9},
{101905590u,6636,9},
{740289177u,6649,9},
{298565713u,6657,9},
{2531292011u,6663,9},
{691148275u,6674,9},
{4084658662u,6691,9},
{2398479240u,6697,9},
{67753863u,6711,9},
{1284356689u,6728,9},
{1672195559u,6734,8},
{4267640610u,6740,8},
{2179174271u,6761,8},
{2154536131u,6768,8},
{4180675781u,6775,8},
{3403504941u,6784,8},
{86520421u,6795,8},
{11251904u,6801,8},
{6774487u,6811,8},
{390201602u,6819,8},
{2006142190u,6831,8},
{2890830793u,6838,8},
{822018448u,6852,8},
{4055125828u,6860,8},
{1790834270u,6869,8},
{2623969160u,6885,8},
{1753414259u,6894,8},
{2035069708u,6901,8},
{55628203u,6908,8},
{3005788552u,6915,8},
{2452219115u,6926,8},
{627535535u,6939,8},
{3537231886u,6948,8},
{2482017624u,6964,8},
{741090084u,6987,8},
{1265391242u,6996,8},
{4039289119u,7005,8},
{301427732u,7019,8},
{4135840458u,7025,8},
{640818791u,7036,8},
{2771538552u,7043,8},
{1086534307u,7051,8},
{1384502824u,7065,8},
{3660088182u,7081,8},
{2688780135u,7089,8},
{2920466844u,7100,8},
{884483972u,7120,8},
{2069146067u,7130,8},
{3385765638u,7146,8},
{1968807591u,7154,8},
{2908631255u,7164,8},
{916547552u,7175,8},
{1873600305u,7190,8},
{1993851908u,7199,8},
{3401388520u,7206,8},
{2841686334u,7214,8},
{788045382u,7222,8},
{1491277511u,7239,8},
{1353120668u,7247,8},
{3889340782u,7255,8},
{743478836u,7263,8},
{301304410u,7273,8},
{1836027715u,7281,8},
{4154065143u,7288,8},
{2941886209u,7294,8},
{3685342204u,7305,8},
{3676349299u,7312,8},
{3285698347u,7322,8},
{3724934023u,7336,8},
{1131912276u,7351,13},
{448402357u,7355,13},
{3061159916u,7363,13},
{3458454463u,7381,13},
{3397143273u,7388,13},
{2311345272u,7397,13},
{4108429845u,7418,13},
{3894672200u,7427,13},
{1127861609u,7448,13},
{682434785u,7466,12},
{4278019151u,7483,12},
{2072156101u,7497,12},
{1739845664u,7512,12},
{1069929536u,7527,12},
{3452201761u,7537,12},
{2307837162u,7553,12},
{4061868990u,7573,12},
{121658888u,7594,12},
{444171386u,7615,12},
{3387490166u,7636,12},
{2948279460u,7653,12},
{2551651283u,7671,12},
{893081117u,7690,12},
{1132262048u,7709,12},
{1876516712u,7728,12},
{728614474u,7735,12},
{2549763894u,7745,12},
{296357396u,7769,12},
{4174679674u,7794,12},
{2667889793u,7802,12},
{3984502180u,7813,12},
{3168702960u,7821,12},
{1488164764u,7836,12},
{4175309224u,7845,12},
{943752001u,7857,12},
{1162065741u,7870,12},
{2518351607u,7884,12},
{1475773103u,7899,12},
{3484649228u,7912,12},
{219613597u,7919,12},
{4250167832u,7943,12},
{699456151u,7967,12},
{2983726598u,7983,12},
{3259477733u,8000,12},
{1951180813u,8014,12},
{65402552u,8023,12},
{1026149675u,8029,12},
{1802742206u,8043,12},
{1486521356u,8061,12},
{2266063097u,8083,12},
{2412056353u,8105,10},
{3288047904u,8120,10},
{444583674u,8127,10},
{1886712733u,8140,10},
{2164484578u,8146,10},
{1353720154u,8151,10},
{2186977100u,8159,10},
{3510150843u,8168,10},
{475220373u,8182,10},
{2589662668u,8197,10},
{48339065u,8204,10},
{3347205726u,8222,10},
{1560980623u,8241,11},
{1147287684u,8248,11},
{3757070668u,8262,11},
{3525819835u,8277,11},
{3410276810u,8292,11},
{2218488798u,8300,11},
{1445631933u,8323,11},
{1491375716u,8346,11},
{2739875593u,8355,11},
{3892551591u,8378,11},
{1783355638u,8396,11},
{3448987385u,8407,11},
{3695398481u,8414,11},
{734217681u,8430,11},
{2594165727u,8447,11},
{3249056020u,8459,11},
{2971866336u,8469,11},
{3852654278u,8490,11},
{3623402354u,8512,11},
{3392937977u,8534,11},
{1641462412u,8556,11},
{516990260u,8564,11},
{887537515u,8592,11},
{2132890591u,8621,11},
{1283517198u,8650,17},
{3989239879u,8662,17},
{2718380883u,8671,17},
{3581397346u,8684,17},
{2222034228u,8688,17},
{2191146052u,8697,17},
{345756458u,8702,17},
{3196165219u,8715,17},
{3338918751u,8734,17},
{1941029835u,8739,17},
{1917016601u,8748,17},
{3039269212u,8768,17},
{507621923u,8789,17},
{2382949506u,8810,17},
{1171614426u,8822,18},
{287906327u,8832,18},
{617517171u,8848,18},
{2850111293u,8868,18},
{2346018232u,8895,18},
{2042703219u,8912,18},
{3521165271u,8933,18},
{2666966727u,8958,18},
{1127131465u,8973,18},
{2647026068u,8983,18},
{1938952078u,8994,18},
{3061199846u,9005,18},
{1737348074u,9026,18},
{1452003510u,9044,18},
{1249425552u,9063,18},
{469291905u,9082,18},
{1891140410u,9092,18},
{741586030u,9109,18},
{4260343491u,9121,18},
{2373455159u,9143,18},
{2046537925u,9166,18},
{2667966721u,9190,18},
{1912215274u,9215,18},
{2287941233u,9240,18},
{2758042359u,9258,18},
{3089277354u,9273,18},
{2515846680u,9285,18},
{456714581u,9304,18},
{2601952180u,9323,18},
{2611638396u,9327,18},
{1922257928u,9343,18},
{2620582743u,9355,18},
{2973836112u,9374,18},
{2321795001u,9390,18},
{562680400u,9407,19},
{3147997943u,9411,19},
{3471458123u,9429,19},
{630371791u,9449,19},
{1074326203u,9470,19},
{4081974053u,9484,19},
{3602674979u,9492,19},
{321739290u,9502,19},
{1542143200u,9511,19},
{4262731174u,9531,19},
{3040635986u,9542,19},
{3715219435u,9567,19},
{782665360u,9584,19},
{1489874736u,9595,19},
{2859440138u,9604,19},
{2014313426u,9619,19},
{3493417227u,9625,20},
{2053223216u,9645,20},
{728350375u,9652,20},
{850991848u,9675,20},
{1089816240u,9680,20},
{679453769u,9705,20},
{1518533038u,9727,20},
{387748548u,9734,20},
{904750859u,9748,20},
{3244501995u,9760,20},
{2242229361u,9773,20},
{1343932732u,9786,20},
{1945374990u,9799,20},
{1909700336u,9811,20},
{569305213u,9830,20},
{2157618379u,9837,20},
{4165683409u,9855,20},
{177270108u,9874,20},
{2645431192u,9889,20},
{2112052861u,9903,20},
{1653666139u,9911,20},
{1747439474u,9926,20},
{4080511798u,9946,20},
{2306538597u,9967,20},
{2588363614u,9978,14},
{1033245328u,9984,14},
{276773164u,10000,14},
{509498602u,10017,14},
{867467158u,10034,14},
{861409633u,10051,14},
{1336872304u,10058,14},
{3228633070u,10066,14},
{4018222598u,10073,14},
{1861786828u,10094,14},
{3251507587u,10102,14},
{3806844075u,10110,14},
{3264692260u,10126,14},
{3678636260u,10146,14},
{3983945033u,10167,14},
{231083307u,10188,14},
{437538602u,10206,14},
{400514754u,10225,14},
{771711535u,10232,14},
{4012021193u,10244,14},
{1070967343u,10252,14},
{908897389u,10264,14},
{290013743u,10277,14},
{1448677353u,10293,14},
{2194326579u,10310,14},
{3314393930u,10314,14},
{1181327175u,10332,15},
{837858166u,10338,15},
{295054921u,10350,15},
{745926877u,10370,15},
{788747387u,10378,15},
{4244420235u,10401,15},
{1621617168u,10421,15},
{1394036463u,10442,15},
{2025593404u,10463,15},
{3817135397u,10484,15},
{3942284983u,10491,15},
{4252008158u,10506,15},
{744705981u,10518,15},
{1949211328u,10536,15},
{2310691317u,10555,15},
{347619240u,10561,15},
{2634305738u,10588,15},
{353883353u,10597,15},
{4212341271u,10613,15},
{3568198617u,10620,15},
{1044954915u,10632,15},
{1229411063u,10640,15},
{1593933419u,10662,15},
{710198397u,10684,15},
{2623428164u,10696,15},
{3955379698u,10715,15},
{1075432268u,10721,15},
{2694714877u,10734,15},
{1543134283u,10743,15},
{2449479409u,10758,15},
{2635962482u,10766,15},
{2771347558u,10784,16},
{4143991942u,10793,16},
{2176659152u,10806,16},
{408970549u,10824,16},
{3868033424u,10843,16},
{4225674290u,10862,16},
{1692272545u,10881,16},
{1824333165u,10898,16},
{3987008919u,10904,16},
{368211810u,10910,16},
{2336777441u,10935,16},
{3650256867u,10961,16},
{3393804037u,10971,16},
{970356638u,10976,16},
{84351789u,10983,16},
{239897677u,10996,16},
{3287439187u,11008,16},
{970385471u,11021,16},
{1058115860u,11027,16},
{2594093022u,11031,16},
{621481054u,11046,16},
{3080673438u,11052,16},
{2172210288u,11065,16},
{2548391185u,11073,16},
{165154707u,11082,16},
{3545667823u,11089,16},
{2999939664u,11095,16},
{1036591958u,11102,16},
{3013282534u,11114,16},
{2908775872u,11126,16},
{4262088844u,11131,16},
{3929093893u,11147,16},
{3319621991u,11162,16},
{3902291871u,11168,16},
{3080461301u,11178,16},
{191916658u,11185,16},
{1981688531u,11197,16},
{858355070u,11203,16},
{1043222410u,11215,16},
{2531412055u,11220,16},
{1565978651u,11231,16},
{2621610858u,11244,16},
{1077420264u,11250,16},
{1341619767u,11265,16},
{447548909u,11272,16},
{3681241380u,11280,16}
};
